### ISSUE TITLE
You´re not developing an Operating System.

### ISSUE THREAD

**Issue by iyksh** [Alter-Net-codes/SkyOS#10]
With all due respect, it's simply not feasible to create an operating system using Python. What you're developing is more accurately described as a CLI-based OS emulator, not a true operating system.

Why is it impossible to build an OS with python?

- Low-level Access: Operating systems require low-level hardware access, which is something Python isn’t designed - 

- Performance: Python is an interpreted language, making it slower and less efficient compared to languages that compile directly to machine 

- Memory Management: OS development involves precise memory management, which Python abstracts away, making it unsuitable for this 

- Dependency on Native Libraries: Python relies heavily on native libraries written in C/C++, which would defeat the purpose of using Python for OS development.

For your goal, I recommend learning languages like C, C++, Rust, Java, or Ada. These are better suited for systems programming and operating system development. I saw in a print that you´re 9-15 years old, that´s not a problem at all to start an OS, but you should start with the right way.

**Comment by KhangDeveloperd** [comment]
Kind of true, to be honest...

**Comment by webbrowser11** [comment]
i know this. we are making not a true OS but a system that can be ran on other systems.

**Comment by webbrowser11** [comment]
please do not critisize our hard work. i have heard this to much.

**Comment by webbrowser11** [comment]
>I saw in a print that you´re 9-15 years old,
also its we thank you.

**Comment by webbrowser11** [comment]
and me and @bambus80 are making a rewrite of this OS in c and lua.
