### ISSUE TITLE
kernel.py

### ISSUE THREAD

**Issue by KhangDeveloperd** [Alter-Net-codes/SkyOS#3]
kernel.py isnt working. When open it, it crashes. Only the BIOS works (And also, KhangDeveloperd is here and I will be the tester)

**Comment by webbrowser11** [comment]
hmm  an you give me a screen shot?

**Comment by webbrowser11** [comment]
noted working on fixing lots of bugs does it just give you an error or close the window (also you cant use windows 3.1-11 for this its Linux.)

**Comment by webbrowser11** [comment]
i fixed almost all bugs. except yes, the bios command not the file. that will be fixed in the final 2.3 bug patch. for now test all commands except bios in the new release 2.4.

**Comment by KhangDeveloperd** [comment]
ok I will test

**Comment by webbrowser11** [comment]
ight i gonna try to get microboy in here!

**Comment by MicroboyLLC** [comment]
So, what do you need me for?

**Comment by MicroboyLLC** [comment]
> ight i gonna try to get microboy in here!

I hopefully fixed it and also added Java support too and a new kernel panic function.
