### ISSUE TITLE
microboy

### ISSUE THREAD

**Issue by ScratchFakemon** [Alter-Net-codes/SkyOS#6]
(yes my issue is microboy)

**Comment by MicroboyLLC** [comment]
So, why exactly is the issue me? Let me guess: coffeeOS is competing with skyOS due to webbrowser11 being so controlling and even threatening to break GitHub's rules over coffeeOS?

**Comment by ScratchFakemon** [comment]
reasons beyond comprehension

**Comment by MicroboyLLC** [comment]
It's because of coffeeOS, isn't it? If you can't prove why I am even the issue, I'm likely _**not**_ the issue as you can't even prove it.

**Comment by KhangDeveloperd** [comment]
Who made coffeeOS? I'm just curious.

**Comment by webbrowser11** [comment]
wth is happnin

**Comment by Cateatacat** [comment]
Argument

**Comment by webbrowser11** [comment]
k this does not belong here.

**Comment by webbrowser11** [comment]
also this is not okay DONT make issues about people even if it is @microboyLLC
